blog/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup_view, name="signup"),
    path('login/', auth_views.LoginView.as_view(template_name="accounts/login.html"), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
]

blog/articles/urls.py
from django.urls import path, include
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.article_list, name="article_list"),
    path('<int:slug>', views.article_detail, name="article_detail"),
]

blog/blog/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('', views.homepage, name="homepage"),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/accounts/models.py
from django.db import models

# Create your models here.

blog/articles/models.py
from django.db import models
from django.contrib.auth.models import User

class Article(models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField()
    img = models.ImageField(blank=True)
    date = models.DateTimeField(auto_now_add=True) # let user set data
    slug = models.SlugField(blank=True)
    #section = if User = administration or users
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + '...'

blog/accounts/views.py
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect

def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('homepage')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})

blog/articles/views.py
from django.shortcuts import render
from .models import Article

# Create your views here.
def article_list(request):
    articles = Article.objects.all().order_by('date')
    return render(request, 'articles/article_list.html', {'articles':articles})

def article_detail(request, slug):
    article = Article.objects.get(pk=slug)
    return render(request, 'articles/article_detail.html', {'article':article})

blog/blog/views.py
from django.shortcuts import render

def homepage(request):
    return render(request, 'base_layout.html')

blog/accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
  <div class="container">
    <h2>Sign up</h2>
    <form method="post" novalidate>
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn btn-primary">Login</button>
    </form>
  </div>
{% endblock %}

blog/accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
  <div class="container">
    <h2>Sign up</h2>
    <form method="post" novalidate>
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn btn-primary">Create an account</button>
    </form>
  </div>
{% endblock %}

blog/articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}

{% block content %}
  <p>{{article.title}}</p>
  <p>{{article.body}}</p>
  <p>{{article.author}}</p>
{% endblock %}

blog/articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}

{% block content %}
  <div class="articles">
    {% for article in articles %}
      <div class="article">
        <h2><a href="{% url 'articles:article_detail' slug=article.id %}">{{article.title}}</a></h2>
        <p>{{article.body}}</p>
        <p>{{article.date}}</p>
      </div>
    {% endfor %}
  </div>
{% endblock %}

blog/templates/base_layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>My Blog</title>
        <link href="https://fonts.googleapis.com/css?family=Peralta" rel="stylesheet">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
        {% block head %}{% endblock %}
    </head>
    <body>
      <h1>Welcome to My Blog</h1>
      <h2><a href="{% url 'accounts:logout'%}">Logout</a></h2>
        <div class="content">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>